# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0c2e79f07d1653fa765734ea3aff90924ea4b14116b71ca592874190fee6147d34b3339cd6e9566b582087034f10c448aa8985ceb23beaf40f3f2524510a7cc

test:
  secret_key_base: efa829a197dce89f3e756b8b0be85bf1e75ab02cef98edc832e3062c436f2edaf149236b48a3a59771111029b99cf840631e445dabd6cd3abc694a3d0fdc3983

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
